name: Create pull request

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build
      
    - name: Run Unit tests
      run: npm run test

    - name: Run linter
      run: yarn run eslint ./src/ --ext .ts,.tsx
