name: Push to master

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: reactapp
        path: build/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3

      - name: Setup SSH
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 22 -t ed25519 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          rsync -azP -e "ssh -i $HOME/.ssh/id_ed25519 -p 22" ./reactapp ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:../var/www/
