name: React CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Run build
      run: npm run build
      
    - name: Run UnitTests
      run: npm run test

    - name: Display structure of downloaded files
      run: ls -R $PWD/*

    - name: Run lint
      uses: super-linter/super-linter@v5
      env:
       DEFAULT_WORKSPACE: UI/UI/build
       DEFAULT_BRANCH: master
       VALIDATE_ALL_CODEBASE: true
       VALIDATE_TYPESCRIPT_STANDARD: true
       VALIDATE_TYPESCRIPT_ES: true
       VALIDATE_TSX: true
       VALIDATE_JSON: true
       VALIDATE_JAVASCRIPT_STANDARD: true
       VALIDATE_JAVASCRIPT_ES: true
       VALIDATE_HTML: true
       VALIDATE_CSS: true
       VALIDATE_YAML: false
       GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: reactapp
        path: build/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R $PWD/*

      - name: Set up SSH key
        run: |
          env
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 22 -t ed25519 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          rsync -azP -e "ssh -i $HOME/.ssh/id_ed25519 -p 22" ./reactapp ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:../var/www/

      
